api_platform:
    defaults:
        pagination_enabled: false
        pagination_client_items_per_page: true
        pagination_client_enabled: true
        pagination_items_per_page: 30
    collection:
        pagination:
            items_per_page_parameter_name: 'count'
        